# Site settings
title: "Archaeological Fish Resource"
blurb: "A digital reference collection of key skeletal elements for more than 90 species of Mediterranean and North Atlantic freshwater and marine fishes."
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
port: 			  4116

# Build settings
#markdown: kramdown
exclude:
  - "README.md"
include: [".nojekyll"]

# Extra plugin to create page per item from data sources eg CSV
# https://github.com/avillafiorita/jekyll-datapage_gen

plugins:
  - jekyll-datapage-generator

page_gen:
  - data: 'fishbones'
    template: 'item'
    dir: 'bones'
    name_expr: 'record["Title"].delete(" ")'
    title: 'Title'

  - data: 'fishbones'
    template: 'element'
    dir: 'Element'
    name_expr: 'record["Element"].delete(" ")'
    title: 'Element'

  - data: 'fishbones'
    template: 'commonName'
    dir: 'CommonName'
    name_expr: 'record["CommonName"].delete(" ")'
    title: 'CommonName'

  - data: 'fishbones'
    template: 'family'
    dir: 'Family'
    name_expr: 'record["Family"].delete(" ")'
    title: 'Family'

  - data: 'fishbones'
    template: 'geographicalRange'
    dir: 'GeographicalRange'
    name_expr: 'record["GeographicalRange"].delete(" ")'
    title: 'GeographicalRange'
